# Generated by Django 5.2.3 on 2025-06-23 02:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=django.utils.timezone.now)),
                ('points_earned', models.IntegerField(default=0)),
                ('gas_q1', models.BooleanField(default=False, verbose_name='エコバッグを使った')),
                ('water_q1', models.BooleanField(default=False, verbose_name='こまめに水を止めた')),
                ('power_q1', models.BooleanField(default=False, verbose_name='衣服で温度調整をした')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.character')),
            ],
            options={
                'unique_together': {('character', 'record_date')},
            },
        ),
    ]
